### ISSUE TITLE
Add support for CODE=rich

### ISSUE THREAD

**Issue by asccc** [dev-community-de/code-formatter#37]
Apparently, XenForo's rich syntax highlighting supports nested CODE bbcodes.
The output looks weird, but it works... see https://dev-community.de/threads/batch-bbcode-syntax-highlighting.159/#post-1024

The parser has to be able to nest CODE bbcodes inside a CODE=rich bbcode and the main-logic has to send those nested CODE blocks to the formatter.

Sounds like fun... 😆 

For reference: 

![grafik](https://user-images.githubusercontent.com/42143765/87371461-b9fe6280-c585-11ea-9813-56aadce0f14d.png)

@jr-cologne i think the formatting is off, because this behavior is not well supported. We probably have to adjust the board-style a bit to make this look right.

Can you create a private repo containing the XenForo source-code or just the bbcode related stuff? 
It would be interesting to see how they do this.

**Comment by jr-cologne** [comment]
The wrong formatting might also have to do with prism.js - the syntax highlighter.

I could create a private repo for the XenForo source code, but I'm not sure whether this complies with the XenForo license agreement. I would probably need a permission for that...
Or do you have any other information on that topic?
If you want, I can open up a support ticket in order to ask them whether such usage for development purposes is allowed.
